Famer.WebUI/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Famer.Entity.ViewModel;
using Famer.Entity.Concrete;
using Famer.Entity.Abstract;
using Famer.Entity.Model;

namespace Famer.WebUI.Controllers
{
    public class LoginController : Controller
    {
		// GET: Login
		private IUserInfoRepository repository;
		private ICartRepository cart;
		//解析依赖项
		public LoginController(IUserInfoRepository repo,ICartRepository cartRe)
		{
			repository = repo;
			cart = cartRe;
		}
        public ActionResult Index() 
        {
            return View();
        }

		[HttpPost]
		public ActionResult Index(LoginViewModel lvm)
		{
			if(repository.CheckLogin(lvm))
			{
				UserInfo info = repository.UserInfos.Where(m => m.Phone == lvm.Phone).FirstOrDefault();
				Session["userinfo"] = info;
				//初始化购物车嗷
				Cart cart1 = cart.Carts.Where(e => e.User_Id == info.UserID).FirstOrDefault();
				//如果为空则表示是第一次登录 
				if(cart1==null)
				{
					Cart cart2 = new Cart { User_Id = info.UserID, Num = 0, Total = 0 };
					//把用户的购物车存入数据库
					cart.AddCart(cart2);
					Session["cart"] = cart2;
				}
				else
				{
					Session["cart"] = cart1;
				}
				return RedirectToRoute(new { controller = "Home", action = "Index" });
			}
			else
			{
				ModelState.AddModelError("Password", "密码验证错误");
				return View();
			}
		}
    }
}

Famer.WebUI/Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Famer.Entity.Model;
using Famer.Entity.Abstract;
using Famer.Entity.ViewModel;
using Famer.WebUI.Models;

namespace Famer.WebUI.Controllers
{
    public class SellerController : Controller
    {
		// GET: Seller
		private IShopRepository repository;
		private IUserInfoRepository userrepository;
		//解析依赖项获取商店表数据
		public SellerController(IShopRepository repo,IUserInfoRepository repo1)
		{
			repository = repo;
			userrepository = repo1;
		}
        public ActionResult Index()
        {
			Shop shop = (Shop)Session["shop"];
			if (Session["userinfo"] == null)//如果用户未登录 则返回登录视图
			{
				return RedirectToRoute(new { controller = "Login", action = "Index" });
			}
			else if (((UserInfo)Session["userinfo"]).UserRole == "普通用户")
			{
				return View("ERSeller", (UserInfo)Session["userinfo"]);
			}
			else if (shop == null)
			{
				return View("Login");
			}
			else
				return View(shop);
        }
		public ActionResult Login()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Login(LoginViewModelForSel lvms)
		{
			if(repository.CheckLoginForSel(lvms))
			{
				Session["shop"] = (Shop)repository.Shops.Where(m => m.Contact == lvms.Phone).FirstOrDefault();
				return View("Index");
			}
			else
			{
				ModelState.AddModelError("Password", "您输入的账户名和密码不匹配，请重新输入");
				return View();
			}
		}

		//当用户为普通用户时返回的视图
		public ActionResult ERSeller(UserInfo info)
		{
			return View(info);
		}

		public ActionResult Enter()
		{
			UserInfo ui = (UserInfo)Session["userinfo"];
			return View(ui);
		}
		
		[HttpPost]
		public ActionResult Enter(ShopFormViewModel sfvm)
		{
			Shop shop = repository.Shops.Where(m => m.Contact == sfvm.Phone).FirstOrDefault();
			if(shop!=null)
			{
				ModelState.AddModelError("Phone", "该手机号已被注册为商家");
				return View();
			}
			else
			{
				repository.AddShop(new Shop
				{
					ShopName = sfvm.ShopName,
					Seller_Id = ((UserInfo)Session["userinfo"]).UserID,
					Contact = sfvm.Phone,
					Address = sfvm.Address,
					IDcard = sfvm.IDcard,
					Password = sfvm.Password,
					BossName = sfvm.BossName,
					CreateTime = DateTime.Now,
					ShopID=ShopID()
				});
				//改变用户身份
				userrepository.ChangeRole((UserInfo)Session["userinfo"]);
				return View("Login");
			}
		}
		public string ShopID()
		{
			Random r = new Random();
			return r.Next(100000, 10000000).ToString();
		}

    }
}

Famer.WebUI/Views/Seller/ERSeller.cshtml
@model Famer.Entity.Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>助农为乐 - 商家后台</title>
    <style type="text/css">
        .wb-center {
            width: 1000px;
            margin: 0 auto;
            margin-top: 80px;
        }

        .zn-seller {
            display: block;
            margin-left: 130px;
            text-decoration: none;
            cursor: pointer;
            position: relative;
            width: 242px;
            height: 40px;
        }

            .zn-seller .zn-title {
                position: absolute;
                left: 0;
                top: 5px;
                font-family: 华文隶书;
                font-size: 32px;
                color: #e21214;
            }

            .zn-seller .z-s {
                position: absolute;
                right: 0;
                top: 10px;
                color: #777;
                font-weight: 600;
            }

            .zn-seller i {
                height: 100%;
                width: 1px;
                background-color: #777;
                position: absolute;
                right: 105px;
                top: 25px;
            }

        .wb-center .wb-per {
            width: 374px;
            margin: 0 auto;
            margin-top: 72px;
        }

        .wb-center .wb-erinfo {
            font-size: 20px;
            font-weight: 700;
        }

        .wb-center .wb-erchange {
            display: block;
            text-align: center;
            margin-top: 24px;
            box-sizing: content-box;
            padding: 25px 100px;
            color: #797979;
            border: 2px solid #797979;
            text-decoration: none;
            transition: all 0.25s ease;
        }

        .wb-center .wb-per .wb-erchange:hover {
            background-color: #797979;
            color: #eee;
        }

        .wb-center .wb-per .wb-fr {
            float: right;
            display: block;
            margin-top: 30px;
            color: #ff0000;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="wb-center">
        <a class="zn-seller">
            <h2 class="zn-title">助农为乐</h2>
            <i class="line"></i>
            <h2 class="z-s">商家后台</h2>
        </a>
        <div class="wb-per">
            <p class="wb-erinfo">您当前登录账号：@Model.UserName，非商家账号，接下来您可能要：</p>
            <a class="wb-erchange" href="@Url.Action("Login")">切换商家账号</a>
            <a class="wb-fr" href="@Url.Action("Enter")">入驻为助农商家 ></a>
        </div>
    </div>
</body>
</html>

Famer.WebUI/Views/Seller/Enter.cshtml
@model Famer.Entity.Model.UserInfo
@{
    ViewBag.Title = "助农为乐 - 商家入驻";
    Layout = "~/Views/Shared/_EnterLayout.cshtml";
}
<link href="~/Content/css/入驻表单样式.css" rel="stylesheet" />
<div id="header">
    <div class="w">
        <div id="logo-2018">
            <a class="zn-seller">
                <h2 class="zn-title" style="margin: 0">助农为乐</h2>
                <i class="line"></i>
                <h2 class="z-s" style="margin: 0">商家入驻</h2>
            </a>
        </div>
        <div class="header-right">
            <div class="help-area">
                <a target="_blank">
                    <i class="icon-help"></i>入驻帮助
                </a>
            </div>
        </div>
    </div>
</div>
<div class="w">
    <div class="form-panel">
        <div class="form-panel-body">
            <div id="app">
                @using (Html.BeginForm("Enter", "Seller", FormMethod.Post, new { @class = "el-form form-horizontal", id = "myForm" }))
                {
                    <div class="m">
                        <div class="m-title">
                            <h4 class="title">入驻联系人信息</h4>
                        </div>
                        <div class="m-content part1">
                            <div class="form-group">
                                <label class="col-md-3 control-label">*联系人姓名</label>
                                <div class="col-md-9">
                                    <input class="form-control" style="width: 50%;float: left" name="BossName" placeholder="请输入联系人姓名" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">*联系人手机</label>
                                <div class="col-md-9">
                                    <input class="form-control" name="Phone" style="width: 50%;float: left" placeholder="输入联系人手机号" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">*联系人电子邮箱</label>
                                <div class="col-md-9">
                                    <p class="form-control-static email-tip">@Model.Email</p>
                                </div>
                                <div class="col-md-6 col-md-offset-3 form-describe-text">
                                    <span>
                                        入驻过程中用于接收助农为乐审核结果、开店账号密码信息，请务必仔细确认。
                                        <br>
                                        该邮箱已经绑定您注册的普通用户，在此继续绑定您的店铺。
                                    </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">*联系人身份证号</label>
                                <div class="col-md-9">
                                    <input class="form-control" name="IDcard" style="width: 50%;float: left" placeholder="输入联系人身份证号" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">*联系人地址</label>
                                <div class="col-md-9">
                                    <input class="form-control" name="Address" style="width: 50%;float: left" placeholder="输入联系人地址" />
                                </div>
                                <div class="col-md-6 col-md-offset-3 form-describe-text">
                                    <span>作为店铺显示地址，格式可选为XX省XX市XX县/区。</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">*店铺登录密码</label>
                                <div class="col-md-9">
                                    <input type="password" name="Password" class="form-control" style="width: 50%;float: left" placeholder="输入登录密码" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">*确认登录密码</label>
                                <div class="col-md-9">
                                    <input type="password" class="form-control" name="Repassword" style="width: 50%;float: left" placeholder="确认登录密码" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">*店铺名字</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control" name="ShopName" style="width: 50%;float: left" placeholder="输入您的店铺名字" />
                                </div>
                                <div class="col-md-6 col-md-offset-3 form-describe-text">
                                    <span>店铺命名应当不包含敏感词汇，否则入驻将不会成功。</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="btn btn-info" id="part1-btn" style="margin-left: 400px">下一步，缴费入驻</div>
                            </div>
                        </div>
                        <div class="m-content part2" style="display: none">
                            <div class="form-group">
                                <h3 style="margin-left: 135px;">请扫描以下二维码完成入驻</h3>
                            </div>
                            <div class="form-group" style="padding-left: 300px">
                                <img src="~/Images/二维码.jpg" />
                            </div>
                            <div class="form-group">
                                <button class="col-md-3 col-md-offset-4 btn btn-info" type="submit">确认入驻</button>
                            </div>
                        </div>
                    </div>
                  }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#part1-btn").click(function () {
            if ($("#myForm").data('bootstrapValidator').isValid()) {
                $(".part1").hide();
                $(".part2").show();
            }
            else {
                $('#myForm').bootstrapValidator('validate');
            }
        });

        //客户端登录验证
        $(".el-form").bootstrapValidator({
            message:'This value is not valid',
            feedbackIcons:{
                valid:'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields:{
                BossName:{
                    validators:{
                        notEmpty:{
                            message:"联系人姓名不能为空"
                        },
                        stringLength:{
                            min:2,
                            max:15,
                            message:"姓名长度不符合规定"
                        },
                        regexp:{
                            //匹配中文和英文
                            regexp:/^[\u4e00-\u9fa5]+$/,
                            message:"姓名只能是由中文字符组成"
                        }
                    }
                },
                Phone:{
                    validators:{
                        notEmpty:{
                            message:"手机号码不能为空"
                        },
                        regexp:{
                            regexp:/^1[0-9]{10}$/,
                            message:"手机号码格式不对，应该为以1开头的11位数字"
                        }
                    }
                },
                IDcard:{
                    validators:{
                        notEmpty:{
                            message:"身份证号不能为空"
                        },
                        regexp:{
                            // 身份证格式验证
                            regexp:/^(^[1-9]\d{7}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}$)|(^((1[1-5])|(2[1-3])|(3[1-7])|(4[1-6])|(5[0-4])|(6[1-5])|71|(8[12])|91)\d{4}((19\d{2}(0[13-9]|1[012])(0[1-9]|[12]\d|30))|(19\d{2}(0[13578]|1[02])31)|(19\d{2}02(0[1-9]|1\d|2[0-8]))|(19([13579][26]|[2468][048]|0[48])0229))((\d{4})|\d{3}[Xx])$)$/,
                            message:"身份证格式错误"
                        }
                    }
                },
                Address:{
                    validators:{
                        notEmpty:{
                            message:"地址不能为空"
                        },
                        regexp:{
                            regexp:/^[\u4e00-\u9fa5]+$/,
                            message:"地址格式不正确"
                        }
                    }
                },
                Password:{
                    validators:{
                        notEmpty:{
                            message:"密码不能为空"
                        },
                        stringLength:{
                            min: 8,
                            max: 16,
                            message:"密码长度必须是8到16个数字、字母的组合"
                        },
                        regexp:{
                            regexp:/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z.]{8,16}$/,
                            message:"密码强度太弱"
                        }
                    }
                },
                Repassword:{
                    validators:{
                        notEmpty:{
                            message:"确认密码不能为空"
                        },
                        identical:{
                            field:"Password",
                            message:"两次输入的密码不一致"
                        }
                    }
                },
                ShopName:{
                    validators:{
                        notEmpty:{
                            message:"店铺名字不能为空"
                        },

                    }
                }
            }
        })
    })
</script>

Famer.WebUI/Views/Seller/Login.cshtml
@using Famer.Entity.ViewModel;
@model LoginViewModelForSel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="~/Content/css/商家登录.css" rel="stylesheet" />
    <title>助农为乐 - 商家登录</title>
    <style type="text/css">
        * {
            padding: 0;
            margin: 0;
        }
        .field-validation-error{
            margin-top: 3px;
            background-color: #fff5d1;
            border: 1px solid #fff5d1;
            line-height: 25px;
            padding-left: 5px;
            position: absolute;
            top: 98px;
        }
    </style>
</head>
<body id="mainframe">
    <div class="w">
        <div class="logo">
            <a>
                <span>助农为乐</span>
                <span>商家后台</span>
                <i class="dot"></i>
            </a>
        </div>
    </div>
    <div id="content">
        <div class="login-wrap">
            <div class="w">
                <div class="login-form">
                    <div class="login-title">
                        <div class="login-text">
                            <span style="color: #999;">助农为乐商家登录</span>
                        </div>
                    </div>
                    <div class="login-tab">
                        <a href="#" class="login-type">
                            账户登录
                        </a>
                    </div>
                    <div style="position: absolute;top: 80px;width: 100%;">
                        @using (Html.BeginForm("Login", "Seller", FormMethod.Post, new { @class = "form" }))
                        {
                            @Html.ValidationSummary(true)
                            <div class="item-info">
                                <input name="Phone" id="Phone" class="text" type="text" maxlength="20" size="20" placeholder="已认证手机号" />
                            </div>
                            <div class="item-info" style="margin: 0">
                                <input name="Password" id="Password" type="password" class="text" placeholder="密码" />
                            </div>
                            @Html.ValidationMessageFor(m => m.Password)
                            <div class="item-info login-btn">
                                <input type="submit" class="btn-entry" value="登&nbsp;&nbsp;录" />
                            </div>
                            <div class="item">
                                <div style="float: left">
                                    <a href="#">没有账户？</a>
                                </div>
                                <div style="float: right">
                                    <a href="#">忘记密码？</a>
                                </div>
                            </div>
                           }
                    </div>
                </div>
            </div>
            <div class="login-banner">
                <div class="w">
                    <div id="banner-bg" class="i-inner">
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>